# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    assignees:
      - nzuguem
    commit-message:
      prefix: "[maven] "
    labels:
      - maven
      - dependencies
    open-pull-requests-limit: 10
    rebase-strategy: auto
      
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
    assignees:
      - nzuguem
    commit-message:
      prefix: "[github-actions] "
    labels:
      - github-actions
    open-pull-requests-limit: 10
    rebase-strategy: auto
