name: CloudEvents Handler

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🏗️ Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21.0.3
          distribution: graalvm
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: true
          native-image-musl: true
          cache: maven
      
      - name: Build Application  
        env:
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          task build-app/ci
    
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/nzuguem/cloudevents-handler:${{ github.ref_name }}
          format: cyclonedx-json
          artifact-name: cloudevents-handler-image-sbom-cyclonedx-json
          output-file: cloudevents-handler-image-sbom-cyclonedx.json

      - name: Scan Image from its SBOM
        uses: anchore/scan-action@v4
        with:
          sbom: cloudevents-handler-image-sbom-cyclonedx.json
          fail-build: false
          by-cve: true
          output-format: table

      - name: Generate Site Folder
        run: |
          mkdir target/site
          cp target/**/*-build-report.html target/site/index.html

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site/

  deploy:
    name: 🚀 Deploy GitHub Pages of Native Build Report
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4